# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oTasjj8bE5M6ROB0lRvSK_Gla7hCOzru
"""

pip install boto3

import boto3

#This code is to just check wether our user is able to get the details of file from s3 bucket
session = boto3.Session(aws_access_key_id = "AKIAVYQHLGXUZR5BNGNC", #source account access key and secrete access key
                        aws_secret_access_key = "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")
s3 = session.resource('s3')
s3bkt = s3.Bucket('aws-source-bucket01')

for se_files in s3bkt.objects.all():
  copy_source = {"Bucket":s3bkt.name,
                 "Key":se_files.key}
  print(copy_source)

source_client = boto3.client(service_name='s3',aws_access_key_id = "AKIAVYQHLGXUZR5BNGNC", #Source account user acess Key and secrete acess key.
                        aws_secret_access_key = "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")
for se_files in s3bkt.objects.all():
  copy_source = {"Bucket":s3bkt.name,
                 "Key":se_files.key}
  source_response = source_client.get_object(Bucket ='aws-source-bucket01',Key=se_files.key)
  dest_client = boto3.client(service_name='s3',aws_access_key_id = "AKIA5FCUAGNGQVYOFD5H", #destination account user acess Key and secrete acess key.
                        aws_secret_access_key = "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")
  dest_client.upload_fileobj(
  source_response['Body'],'aws-dest-bucket01',Key=se_files.key)
#dest_response = dest_client.get_object(Bucket ='aws-source-bucket01',Key='se_files.key')